blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogsView.as_view(), name='blog_list'),
    path("<int:pk>/", views.BlogDetailView.as_view(), name='blog_detail'),
]

hiking_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.BlogsView.as_view(), name='blog_list'),
    path('filter/', views.FilterBlogsView.as_view(), name='filter'),
    path('blog/', include('blog.urls')),
    path("blog/<int:pk>/update/", views.BlogUpdateView.as_view(), name='update'),
    path("blog/<int:pk>/delete/", views.BlogDeleteView.as_view(), name='delete'),

    # Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),

    # Blogs
    path('create/', views.BlogCreateView.as_view(), name='create'),
    path('myblogs/', views.MyBlogsView, name='myblogs'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Difficulty(models.Model):
    title = models.CharField("Difficulty", max_length=30)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Difficulty"


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='yes', blank=True, default='/yes/default.png')
    height = models.IntegerField()
    difficulty = models.ForeignKey(Difficulty, verbose_name="Difficulty", on_delete=models.SET_NULL, null=True)
    route = models.URLField(blank=True)
    completed = models.BooleanField(null=True, default=False)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + ' | ' + str(self.user)

    def get_absolute_url(self):
        return reverse('myblogs')

blog/forms.py
from django.forms import ModelForm
from django import forms
from .models import Blog


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'description', 'height', 'image', 'difficulty']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'height': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'difficulty': forms.Select(attrs={'class': 'form-control', 'selected': 'Выберите сложность...'}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from .models import Blog, Difficulty
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User, AnonymousUser
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from .forms import BlogForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required


class Diffs:
    def get_diffs(self):
        return Difficulty.objects.all()


class BlogsView(Diffs, ListView):
    """Список маршрутов"""
    model = Blog
    queryset = Blog.objects.all()


class BlogDetailView(Diffs, DetailView):
    """Полное описание маршрута"""
    model = Blog
    slug_field = "url"


def MyBlogsView(request):
    blogs = Blog.objects.filter(user=request.user)
    return render(request, 'blog/myblogs.html', {'blogs': blogs})


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'description', 'height', 'image', 'difficulty']
    template_name = 'blog/blog_update_form.html'


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('myblogs')
    template_name = 'blog/blog_delete.html'


def signupuser(request):
    if request.method == 'GET':
        return render(request, 'blog/signupuser.html', {'form': UserCreationForm})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('blog_list')
            except IntegrityError:
                return render(request, 'blog/signupuser.html',
                              {'form': UserCreationForm, 'error': 'Имя пользователя уже занято'})
        else:
            return render(request, 'blog/signupuser.html', {'form': UserCreationForm, 'error': 'Пароли не совпадают'})


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'blog/loginuser.html', {'form': AuthenticationForm})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'blog/loginuser.html', {'form': AuthenticationForm, 'error': 'Неверное сочетание: логин, пароль'})
        else:
            login(request, user)
            return redirect('blog_list')


def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('blog_list')


class FilterBlogsView(Diffs, ListView):
    """Фильтр маршрутов"""
    def get_queryset(self):
        queryset = Blog.objects.filter(difficulty__in=self.request.GET.getlist('diff'))
        return queryset

blog/templates/blog/base.html
<!doctype html>
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static 'blog/icon-mountains.png' %}">

  <title>Горные маршруты</title>
</head>
<body>
<nav class="navbar navbar-dark bg-primary">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blog_list' %}">
          <span style="font-family: cursive; font-weight: bold;">Горные маршруты</span>
    </a>

    <ul class="nav">
            {% if user.is_authenticated %}
                <li class="nav-item {{ current }}">
                    <a class="nav-link" href="{% url 'myblogs' %}" style="color: white;">Мои маршруты</a>
                </li>
                <li class="nav-item">
                    <a href="#" onclick="$('#signOutBtn').click()" class="nav-link" style="color: white;">Выйти</a>
                    <form style='display: none;' method="POST" action="{% url 'logoutuser' %}">
                        {% csrf_token %}
                        <button id="signOutBtn" type="submit">Выйти</button>
                    </form>
                </li>
            {% else %}
      <li class="nav-item">
      <a class="nav-link active" style="color:white;" aria-current="page" href="{% url 'signupuser' %}">Зарегистрироваться</a>
      </li>
      <li class="nav-item">
      <a class="nav-link active" style="color:white;" aria-current="page" href="{% url 'loginuser' %}">Войти</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

  {% block content %}{% endblock %}

<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="{% url 'blog_list' %}" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">&copy; 2021 Company, Inc</p>
  </footer>
</div>

<style>
  .b-example-divider {
  height: 3rem;
  background-color: rgba(0, 0, 0, .1);
  border: solid rgba(0, 0, 0, .15);
  border-width: 1px 0;
  box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
}
</style>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/blog_delete.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Удалить</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <p>Вы действительно хотите удалить "{{ object }}"?</p>
            {{ form.as_p }}
            <button class="btn btn-danger" type="submit">Удалить</button>
            </form>
        </div>
    </div>
    </div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "blog/base.html" %}

{% load static %}

{% block content %}

<div class="container">
    <center><br>
    <h2>{{ blog.title }}</h2><br>
    <img src="{{ blog.image.url }}" class="img-fluid mb-2">
    </center>
    <h6>{{ blog.date }}</h6>
    <h5>Высота: {{ blog.height }} метров</h5>
    <h5>Сложность: {{ blog.difficulty}}</h5>
    <p style="text-indent: 25px;">{{ blog.description|safe }}</p>
    <h5><a href=" {{ blog.route }} ">Link</a></h5>




</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>New Blog</h2>
        </div>
    </div>

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
            </form>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/blog_list.html
{% extends "blog/base.html" %}

{% load static %}

{% block content %}

<div class="container text-center" id="content">
    <h1><b>Маршруты выходного дня: горы Алматы</b></h1><br>
    <img src="{% static 'blog/mountains.jpg' %}" class="img-fluid" style="align:center;">
</div><br>

<div class="container">
    <h2>Есть множество однодневных пешеходных маршрутов в Алматинских горах, называемых Заилийским Алатау. Этот горный хребет является северной частью Тянь-Шаня️. Я расскажу вам об этих тропах.</h2><br>
    <div class="row">
        <div class="col">
            <form action="{% url 'filter' %}" method="GET">
            <h3 class="sear-head editContent">Сложность</h3>
             <ul class="w3layouts-box-list">
            {% for diff in view.get_diffs %}
                <li class="editContent">
                    <input type="checkbox" class="form-check-input" name="diff" value="{{ diff.id }}">
                    <span class="span editContent">{{ diff.title }}</span>
                </li>
            {% endfor %}
            </ul>
            <button type="submit" class="btn btn-primary">Найти</button>
            </form>
        </div>
        <div class="col-10">
            <div class="row">
                {% for blog in blog_list %}
                <div class="col"><br>
                        <div class="card" style="width: 16rem;">
                            <img src="{{ blog.image.url }}" class="card-img-top">
                            <div class="card-body">
                                <a href="{% url 'blog:blog_detail' blog.id %}">
                                <h5 class="card-title">{{ blog.title }}</h5></a>
                                <p class="card-text">{{ blog.difficulty }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div><br>
</div>

<style>

    #content {
        margin-top: 30px;
    }
    .card:hover {
         transform: scale(1.1);
                 }

    .card {
        transition: transform 0.2s ease;
            }
    .card-body{
        height: 150px;
    }
    .card {
    box-shadow: 0 4px 6px 0 rgba(22, 22, 26, 0.18);
    border-radius: 0;
    border: 0;
            }

</style>

{% endblock %}

blog/templates/blog/blog_update_form.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Изменить {{ object }}</h2>
        </div>
    </div>

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.as_p }}
            <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/createblog.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
<h1>Создать</h1>

<h2>{{ error }}</h2>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать</button>
</form>

{% endblock %}

blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% load static %}

{% block content %}
<div class="container">

    <h2>{{ blog.title }}</h2>
    <center>
    <img src="{{ blog.image.url }}" class="img-fluid mb-2">
    </center>
    <h4>{{ blog.date }}</h4>
    <h4>Высота: {{ blog.height }} метров</h4>
    <h4>Сложность: {{ blog.difficulty}}</h4>
    <h4>{{ blog.description|safe }}</h4>
    <h4><a href=" {{ blog.route }} ">Link</a></h4>


</div>
{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}

{% load static %}

{% block content %}
<div class="container text-center">
    <h1><b>Маршруты выходного дня: горы Алматы</b></h1>
<!--<h3 class="text-center mb-5"> {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>-->
    <img src="{% static 'blog/mountains.jpg' %}" class="img-fluid">
</div><br>
<div class="container">
    <h2>Есть множество однодневных пешеходных маршрутов в Алматинских горах, называемых Заилийским Алатау. Этот горный хребет является северной частью Тянь-Шаня⛰️. Я расскажу вам о 10 тропах.</h2><br>
<div class="row">
    {% for blog in blogs %}
    <div class="col-lg-4 col-md-4">
    <a href="{% url 'blog:detail' blog.id %}">
        <img src="{{ blog.image.url }}" class="img-fluid mb-2" height="350" width="350">
        <h2>{{ blog.title }}</h2>
    </a>
    <p>{{ blog.difficulty }}</p>


    </div>
    {% endfor %}
</div>
</div>
{% endblock %}

blog/templates/blog/loginuser.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Login</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            <hr>
            <div class="text-center">
                Need an account? <a href="{% url 'signupuser' %}">Sign Up here</a>
            </div>
        </div>
    </div>
{% endblock %}
<h2>{{ error }}</h2>

blog/templates/blog/myblogs.html
{% extends "blog/base.html" %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-10">
            <div class="row">
                {% for blog in blogs %}
                <div class="col"><br>
                        <div class="card" style="width: 16rem;">
                            <img src="{{ blog.image.url }}" class="card-img-top">
                            <div class="card-body">
                                <a href="{% url 'blog:blog_detail' blog.id %}">
                                <h5 class="card-title">{{ blog.title }}</h5></a>
                                <p class="card-text">{{ blog.difficulty }}</p>
                                <a href="{% url 'update' blog.id %}">Изменить</a>
                                <a href="{% url 'delete' blog.id %}">Удалить</a>
                            </div>
                        </div>
                </div>
                {% endfor %}
                <div class="col"><br>
                        <div class="card" style="width: 16rem;">
                            <div class="card-body">
                                <a href="{% url 'create' %}"><img src="{% static 'blog/logo.jpg' %}" class="card-img-top" style="width: 10%;">
                                Добавить новый маршрут</a>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div><br>
</div>

<style>
    #content {
        margin-top: 30px;
    }
    .card:hover {
         transform: scale(1.1);
                 }

    .card {
        transition: transform 0.2s ease;
            }
    .card-body{
        height: 150px;
    }
    .card {
    box-shadow: 0 4px 6px 0 rgba(22, 22, 26, 0.18);
    border-radius: 0;
    border: 0;
            }

</style>

{% endblock %}

blog/templates/blog/signupuser.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Sign Up</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                    <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know if someone has taken it already.</small>
                </div>
                <div class="form-group">
                    <label for="password1">Password</label>
                    <input type="password" name="password1" class="form-control" id="password1">
                </div>
                <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input type="password" name="password2" class="form-control" id="password2">
                </div>
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
            <hr>
            <div class="text-center">
                Do you already have an account? <a href="{% url 'loginuser' %}">Login here</a>
            </div>
        </div>
    </div>
{% endblock %}